### ISSUE TITLE
Entrega hito 4

### ISSUE THREAD

**Issue by mmaguero** [mmaguero/MII-CC16-17#7]
Actualizar repo de proyecto / ejercicios / asignatura

**Comment by joseangeldiazg** [comment]
Corregido y funcionando correctamente. 

<img width="607" alt="captura de pantalla 2017-01-09 a las 21 08 36" src="https://cloud.githubusercontent.com/assets/10519534/21781483/ddd29212-d6af-11e6-96dd-5d64698c2811.png">
